RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

# RGB_MATRIX_ENABLE  = no
# RGBLIGHT_ENABLE    = yes

MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = yes
OLED_DRIVER_ENABLE = yes

